### ISSUE TITLE
Trim a video

### ISSUE THREAD

**Issue by aditya-protonn** [googleapis/java-video-transcoder#202]
I didn't find a way to trim down a video given start-time, end-time. Let's say the input video is of duration 60secs and I want to cut out the duration between start-time=20secs and end-time=30secs from the input video. Is there any way to do it with current feature set ? I only found cropping and adding overlays.

**Comment by Neenu1995** [comment]
Please take a look at the [client library documentation](https://googleapis.dev/java/google-cloud-video-transcoder/latest/index.html) to see a list of all available features.

**Comment by Neenu1995** [comment]
Refer `editList` in the `JobConfig` for more info: https://cloud.google.com/transcoder/docs/reference/rest/v1/JobConfig

The following partial config produces an output video 5 seconds long:
```
    "editList": [
      {
        "key": "atom0",
        "inputs": [
          "input0"
        ],
        "endTimeOffset": "15s",
        "startTimeOffset": "10s"
      }
    ],
    "inputs": [
          {
            "key": "input0",
            "uri": "gs://your-bucket/your-audio.mp4"
          }
        ],
```
