### ISSUE TITLE
Can't transcode to .ts

### ISSUE THREAD

**Issue by juanaguss** [googleapis/java-video-transcoder#289]
Hello! We've been trying to use Transcoder API to convert a .mp4 to a .ts, but when we try to set a custom template based on the one in [the documentation](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/HEAD/media/transcoder/src/main/java/com/example/transcoder/CreateJobTemplate.java) and change `.setContainer("mp4")` to `.setContainer("ts")`, everything seems to work fine but we can not see the transcoded video. However, if I use `mp4` as a parameter, the video appears correctly on the output uri. Are we doing something wrong in here or is it an error?

**Comment by conlean** [comment]
as @juanaguss mentioned. We are using the Java library and this is our code. Thanks for your help. We are blocked with that.
/
`    private CreateJobRequest getCustomJobRequest(String videoName) {
        String inputUrl = String.format("%s%s", inputUri, videoName);

        VideoStream videoStream0 =
                VideoStream.newBuilder()
                        .setH264(
                                VideoStream.H264CodecSettings.newBuilder()
                                        .setBitrateBps(550000)
                                        .setFrameRate(60)
                                        .setHeightPixels(360)
                                        .setWidthPixels(640).build()
                        )
                        .build();

        VideoStream videoStream1 =
                VideoStream.newBuilder()
                        .setH264(
                                VideoStream.H264CodecSettings.newBuilder()
                                        .setBitrateBps(2500000)
                                        .setFrameRate(60)
                                        .setHeightPixels(720)
                                        .setWidthPixels(1280))
                        .build();

        AudioStream audioStream0 =
                AudioStream.newBuilder().setCodec("aac").setBitrateBps(64000).build();

        JobConfig config =
                JobConfig.newBuilder()
                        .addInputs(Input.newBuilder().setKey("input0").setUri(inputUrl))
                        .setOutput(Output.newBuilder().setUri(outputUri))
                        .addElementaryStreams(
                                ElementaryStream.newBuilder()
                                        .setKey("video_stream0")
                                        .setVideoStream(videoStream0))
                        .addElementaryStreams(
                                ElementaryStream.newBuilder()
                                        .setKey("video_stream1")
                                        .setVideoStream(videoStream1))
                        .addElementaryStreams(
                                ElementaryStream.newBuilder()
                                        .setKey("audio_stream0")
                                        .setAudioStream(audioStream0))
                        .addMuxStreams(
                                MuxStream.newBuilder()
                                        .setKey("sd")
                                        .setContainer("fmp4")
                                        .addElementaryStreams("video_stream0")
                                        .addElementaryStreams("audio_stream0")
                                        .build())
                        .addMuxStreams(
                                MuxStream.newBuilder()
                                        .setKey("hd")
                                        .setContainer("ts")
                                        .addElementaryStreams("video_stream1")
                                        .addElementaryStreams("audio_stream0")
                                        .build())
                        .setPubsubDestination(PubsubDestination.newBuilder().setTopic(jobCompletedTopic).build())
                        .build();

        return
                CreateJobRequest.newBuilder()
                        .setJob(
                                Job.newBuilder()
                                        .setInputUri(inputUrl)
                                        .setOutputUri(outputUri)
                                        .setConfig(config)
                                        .setName(videoName)
                                        .build())
                        .setParent(LocationName.of(projectId, location).toString())
                        .build();

    }`

**Comment by conlean** [comment]
Adding a Manifest to jobConfig it works.

`.addManifests(
                                Manifest.newBuilder()
                                        .setType(Manifest.ManifestType.HLS)
                                        .addMuxStreams("media-hd")
                                        .build()`
